/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.telavisual;

import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCentro = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        entrada1 = new javax.swing.JTextField();
        entrada2 = new javax.swing.JTextField();
        jButtonSoma = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplicador = new javax.swing.JButton();
        jButtonDivisor = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        op = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(20, 20, 20));
        jPanelPrincipal.setForeground(new java.awt.Color(30, 30, 30));

        jPanelCentro.setBackground(new java.awt.Color(30,30,30));
        jPanelCentro.setBackground(new java.awt.Color(70, 70, 70));
        jPanelCentro.setForeground(new java.awt.Color(30, 30, 30));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("CALCULADERA");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        entrada1.setBackground(new java.awt.Color(153, 153, 153));
        entrada1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entrada1.setForeground(new java.awt.Color(255, 255, 255));
        entrada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrada1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        entrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada1ActionPerformed(evt);
            }
        });

        entrada2.setBackground(new java.awt.Color(153, 153, 153));
        entrada2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entrada2.setForeground(new java.awt.Color(255, 255, 255));
        entrada2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrada2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        entrada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada2ActionPerformed(evt);
            }
        });

        jButtonSoma.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButtonSoma.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSoma.setBackground(new java.awt.Color(86,86,86));
        jButtonSoma.setText("+");
        jButtonSoma.setAlignmentY(0.0F);
        jButtonSoma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButtonSubtracao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubtracao.setBackground(new java.awt.Color(86,86,86));
        jButtonSubtracao.setText("-");
        jButtonSubtracao.setAlignmentY(0.0F);
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonMultiplicador.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButtonMultiplicador.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiplicador.setBackground(new java.awt.Color(86,86,86));
        jButtonMultiplicador.setText("x");
        jButtonMultiplicador.setAlignmentY(0.0F);
        jButtonMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicadorActionPerformed(evt);
            }
        });

        jButtonDivisor.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButtonDivisor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivisor.setBackground(new java.awt.Color(86,86,86));
        jButtonDivisor.setText("÷");
        jButtonDivisor.setAlignmentY(0.0F);
        jButtonDivisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisorActionPerformed(evt);
            }
        });

        jButtonCalcular.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcular.setBackground(new java.awt.Color(86,86,86));
        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.setAlignmentY(0.0F);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setBackground(new java.awt.Color(86,86,86));
        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.setPreferredSize(new java.awt.Dimension(205, 59));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        op.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        op.setForeground(new java.awt.Color(255, 255, 255));
        op.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op.setText(" ");
        op.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entrada2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(entrada1)))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitulo)
                .addGap(64, 64, 64)
                .addComponent(entrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op)
                .addGap(18, 18, 18)
                .addComponent(entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonSoma)
                    .addComponent(jButtonSubtracao)
                    .addComponent(jButtonMultiplicador)
                    .addComponent(jButtonDivisor))
                .addGap(44, 44, 44)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalcular)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jPanelCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //variavel para determinar o operador de calculo
    private int operador;
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        float valor1, valor2;
        valor1 = Float.parseFloat(entrada1.getText());
        valor2 = Float.parseFloat(entrada2.getText());
        switch (operador) {
            case 1:
                JOptionPane.showMessageDialog(jPanelPrincipal, "RESULTADO: "+(valor1+valor2));
            break;
            case 2:
                JOptionPane.showMessageDialog(jPanelPrincipal, "RESULTADO: "+(valor1*valor2));
            break;
            case 3:
                JOptionPane.showMessageDialog(jPanelPrincipal, "RESULTADO: "+(valor1/valor2));
            break;
            case 4:
                JOptionPane.showMessageDialog(jPanelPrincipal, "RESULTADO: "+(valor1-valor2));
            break;
            default:
                JOptionPane.showMessageDialog(jPanelPrincipal, "SELECIONE UM OPERADOR", "ERRO", JOptionPane.ERROR_MESSAGE);
            break;
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonDivisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisorActionPerformed
        operador=3;
        op.setText("÷");
    }//GEN-LAST:event_jButtonDivisorActionPerformed

    private void jButtonMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicadorActionPerformed
        operador=2;
        op.setText("x");
    }//GEN-LAST:event_jButtonMultiplicadorActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        operador=4;
        op.setText("-");
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        operador=1;
        op.setText("+");
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void entrada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada2ActionPerformed

    }//GEN-LAST:event_entrada2ActionPerformed

    private void entrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrada1ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        entrada1.setText(" ");
        entrada2.setText(" ");
        op.setText(" ");
    }//GEN-LAST:event_jButtonLimparActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entrada1;
    private javax.swing.JTextField entrada2;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonDivisor;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMultiplicador;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel op;
    // End of variables declaration//GEN-END:variables
}
