/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.treinodigitacao;

import java.awt.Color;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author jhonn
 */
public class TelaDigitacao extends javax.swing.JFrame {
    private static final String teclasPossiveis = "\t\n~1234567890+-QWERTYUIOP[]\\ASDFGHJKL:*ZXCVBNM,.?^<>v ";
    /**
     * Creates new form TelaDigitacao
     */
    public TelaDigitacao() {
        initComponents();
        panelPrincipal.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,java.util.Collections.emptySet());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradaTexto = new javax.swing.JTextArea();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        SHIFT = new javax.swing.JButton();
        CAPS = new javax.swing.JButton();
        TAB = new javax.swing.JButton();
        abreColchete = new javax.swing.JButton();
        fechaColchete = new javax.swing.JButton();
        barra = new javax.swing.JButton();
        doisPontos = new javax.swing.JButton();
        veses = new javax.swing.JButton();
        virgula = new javax.swing.JButton();
        ponto = new javax.swing.JButton();
        interroga = new javax.swing.JButton();
        ENTER = new javax.swing.JButton();
        setaCima = new javax.swing.JButton();
        setaEsquerda = new javax.swing.JButton();
        setaDireita = new javax.swing.JButton();
        setaBaixo = new javax.swing.JButton();
        SPACE = new javax.swing.JButton();
        tiu = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        BACKSPACE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teclado Virtual");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(153, 204, 255));
        panelPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelPrincipalFocusLost(evt);
            }
        });
        panelPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyTyped(evt);
            }
        });

        entradaTexto.setEditable(false);
        entradaTexto.setBackground(new java.awt.Color(255, 255, 255));
        entradaTexto.setColumns(20);
        entradaTexto.setForeground(new java.awt.Color(0, 0, 0));
        entradaTexto.setRows(5);
        entradaTexto.setCaretColor(new java.awt.Color(0, 0, 0));
        entradaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(entradaTexto);

        A.setBackground(java.awt.Color.darkGray);
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("A");

        B.setBackground(java.awt.Color.darkGray);
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("B");

        C.setBackground(java.awt.Color.darkGray);
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("C");

        D.setBackground(java.awt.Color.darkGray);
        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setText("D");

        E.setBackground(java.awt.Color.darkGray);
        E.setForeground(new java.awt.Color(255, 255, 255));
        E.setText("E");

        F.setBackground(java.awt.Color.darkGray);
        F.setForeground(new java.awt.Color(255, 255, 255));
        F.setText("F");

        G.setBackground(java.awt.Color.darkGray);
        G.setForeground(new java.awt.Color(255, 255, 255));
        G.setText("G");

        H.setBackground(java.awt.Color.darkGray);
        H.setForeground(new java.awt.Color(255, 255, 255));
        H.setText("H");

        I.setBackground(java.awt.Color.darkGray);
        I.setForeground(new java.awt.Color(255, 255, 255));
        I.setText("I");

        J.setBackground(java.awt.Color.darkGray);
        J.setForeground(new java.awt.Color(255, 255, 255));
        J.setText("J");

        K.setBackground(java.awt.Color.darkGray);
        K.setForeground(new java.awt.Color(255, 255, 255));
        K.setText("K");

        L.setBackground(java.awt.Color.darkGray);
        L.setForeground(new java.awt.Color(255, 255, 255));
        L.setText("L");

        M.setBackground(java.awt.Color.darkGray);
        M.setForeground(new java.awt.Color(255, 255, 255));
        M.setText("M");

        N.setBackground(java.awt.Color.darkGray);
        N.setForeground(new java.awt.Color(255, 255, 255));
        N.setText("N");

        O.setBackground(java.awt.Color.darkGray);
        O.setForeground(new java.awt.Color(255, 255, 255));
        O.setText("O");

        P.setBackground(java.awt.Color.darkGray);
        P.setForeground(new java.awt.Color(255, 255, 255));
        P.setText("P");

        Q.setBackground(java.awt.Color.darkGray);
        Q.setForeground(new java.awt.Color(255, 255, 255));
        Q.setText("Q");

        R.setBackground(java.awt.Color.darkGray);
        R.setForeground(new java.awt.Color(255, 255, 255));
        R.setText("R");

        S.setBackground(java.awt.Color.darkGray);
        S.setForeground(new java.awt.Color(255, 255, 255));
        S.setText("S");

        T.setBackground(java.awt.Color.darkGray);
        T.setForeground(new java.awt.Color(255, 255, 255));
        T.setText("T");

        U.setBackground(java.awt.Color.darkGray);
        U.setForeground(new java.awt.Color(255, 255, 255));
        U.setText("U");

        V.setBackground(java.awt.Color.darkGray);
        V.setForeground(new java.awt.Color(255, 255, 255));
        V.setText("V");
        V.setActionCommand("LETRA_V");

        W.setBackground(java.awt.Color.darkGray);
        W.setForeground(new java.awt.Color(255, 255, 255));
        W.setText("W");

        X.setBackground(java.awt.Color.darkGray);
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setText("X");

        Y.setBackground(java.awt.Color.darkGray);
        Y.setForeground(new java.awt.Color(255, 255, 255));
        Y.setText("Y");

        Z.setBackground(java.awt.Color.darkGray);
        Z.setForeground(new java.awt.Color(255, 255, 255));
        Z.setText("Z");

        SHIFT.setBackground(java.awt.Color.darkGray);
        SHIFT.setForeground(new java.awt.Color(255, 255, 255));
        SHIFT.setText("Shift");

        CAPS.setBackground(java.awt.Color.darkGray);
        CAPS.setForeground(new java.awt.Color(255, 255, 255));
        CAPS.setText("Caps");

        TAB.setBackground(java.awt.Color.darkGray);
        TAB.setForeground(new java.awt.Color(255, 255, 255));
        TAB.setText("Tab");

        abreColchete.setBackground(java.awt.Color.darkGray);
        abreColchete.setForeground(new java.awt.Color(255, 255, 255));
        abreColchete.setText("[");

        fechaColchete.setBackground(java.awt.Color.darkGray);
        fechaColchete.setForeground(new java.awt.Color(255, 255, 255));
        fechaColchete.setText("]");

        barra.setBackground(java.awt.Color.darkGray);
        barra.setForeground(new java.awt.Color(255, 255, 255));
        barra.setText("\\");

            doisPontos.setBackground(java.awt.Color.darkGray);
            doisPontos.setForeground(new java.awt.Color(255, 255, 255));
            doisPontos.setText(":");

            veses.setBackground(java.awt.Color.darkGray);
            veses.setForeground(new java.awt.Color(255, 255, 255));
            veses.setText("*");

            virgula.setBackground(java.awt.Color.darkGray);
            virgula.setForeground(new java.awt.Color(255, 255, 255));
            virgula.setText(",");

            ponto.setBackground(java.awt.Color.darkGray);
            ponto.setForeground(new java.awt.Color(255, 255, 255));
            ponto.setText(".");

            interroga.setBackground(java.awt.Color.darkGray);
            interroga.setForeground(new java.awt.Color(255, 255, 255));
            interroga.setText("?");

            ENTER.setBackground(java.awt.Color.darkGray);
            ENTER.setForeground(new java.awt.Color(255, 255, 255));
            ENTER.setText("Enter");

            setaCima.setBackground(java.awt.Color.darkGray);
            setaCima.setForeground(new java.awt.Color(255, 255, 255));
            setaCima.setText("^");

            setaEsquerda.setBackground(java.awt.Color.darkGray);
            setaEsquerda.setForeground(new java.awt.Color(255, 255, 255));
            setaEsquerda.setText("<");

            setaDireita.setBackground(java.awt.Color.darkGray);
            setaDireita.setForeground(new java.awt.Color(255, 255, 255));
            setaDireita.setText(">");

            setaBaixo.setBackground(java.awt.Color.darkGray);
            setaBaixo.setForeground(new java.awt.Color(255, 255, 255));
            setaBaixo.setText("v");
            setaBaixo.setActionCommand("SETA_BAIXO");

            SPACE.setBackground(java.awt.Color.darkGray);
            SPACE.setForeground(new java.awt.Color(255, 255, 255));
            SPACE.setText("Space");

            tiu.setBackground(java.awt.Color.darkGray);
            tiu.setForeground(new java.awt.Color(255, 255, 255));
            tiu.setText("~");

            n1.setBackground(java.awt.Color.darkGray);
            n1.setForeground(new java.awt.Color(255, 255, 255));
            n1.setText("1");

            n2.setBackground(java.awt.Color.darkGray);
            n2.setForeground(new java.awt.Color(255, 255, 255));
            n2.setText("2");

            n3.setBackground(java.awt.Color.darkGray);
            n3.setForeground(new java.awt.Color(255, 255, 255));
            n3.setText("3");

            n4.setBackground(java.awt.Color.darkGray);
            n4.setForeground(new java.awt.Color(255, 255, 255));
            n4.setText("4");

            n5.setBackground(java.awt.Color.darkGray);
            n5.setForeground(new java.awt.Color(255, 255, 255));
            n5.setText("5");

            n6.setBackground(java.awt.Color.darkGray);
            n6.setForeground(new java.awt.Color(255, 255, 255));
            n6.setText("6");

            n7.setBackground(java.awt.Color.darkGray);
            n7.setForeground(new java.awt.Color(255, 255, 255));
            n7.setText("7");

            n8.setBackground(java.awt.Color.darkGray);
            n8.setForeground(new java.awt.Color(255, 255, 255));
            n8.setText("8");

            n9.setBackground(java.awt.Color.darkGray);
            n9.setForeground(new java.awt.Color(255, 255, 255));
            n9.setText("9");

            n0.setBackground(java.awt.Color.darkGray);
            n0.setForeground(new java.awt.Color(255, 255, 255));
            n0.setText("0");

            menos.setBackground(java.awt.Color.darkGray);
            menos.setForeground(new java.awt.Color(255, 255, 255));
            menos.setText("-");

            mais.setBackground(java.awt.Color.darkGray);
            mais.setForeground(new java.awt.Color(255, 255, 255));
            mais.setText("+");

            BACKSPACE.setBackground(new java.awt.Color(51, 51, 51));
            BACKSPACE.setForeground(new java.awt.Color(255, 255, 255));
            BACKSPACE.setText("Backspace");

            javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
            panelPrincipal.setLayout(panelPrincipalLayout);
            panelPrincipalLayout.setHorizontalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(tiu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(n0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mais)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BACKSPACE))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TAB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SHIFT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(Q)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(E)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(R)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(T)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Y)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(U)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(I)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(O)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(P)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(abreColchete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fechaColchete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(barra))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(A)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(D)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(F)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(G)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(H)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(J)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(K)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(doisPontos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(veses)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ENTER))))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(CAPS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Z)
                            .addGap(6, 6, 6)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(X)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(C)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(V)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(N)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(M)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(virgula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ponto))
                                .addComponent(SPACE, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(setaEsquerda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(setaBaixo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(setaDireita))
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(interroga)
                                    .addGap(18, 18, 18)
                                    .addComponent(setaCima))))
                        .addComponent(jScrollPane1))
                    .addContainerGap(16, Short.MAX_VALUE))
            );
            panelPrincipalLayout.setVerticalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tiu)
                        .addComponent(n1)
                        .addComponent(n2)
                        .addComponent(n3)
                        .addComponent(n4)
                        .addComponent(n5)
                        .addComponent(n6)
                        .addComponent(n7)
                        .addComponent(n8)
                        .addComponent(n9)
                        .addComponent(n0)
                        .addComponent(menos)
                        .addComponent(mais)
                        .addComponent(BACKSPACE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(E)
                        .addComponent(I)
                        .addComponent(Q)
                        .addComponent(W)
                        .addComponent(R)
                        .addComponent(T)
                        .addComponent(Y)
                        .addComponent(U)
                        .addComponent(O)
                        .addComponent(P)
                        .addComponent(TAB)
                        .addComponent(abreColchete)
                        .addComponent(fechaColchete)
                        .addComponent(barra))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(S)
                        .addComponent(A)
                        .addComponent(D)
                        .addComponent(F)
                        .addComponent(G)
                        .addComponent(H)
                        .addComponent(J)
                        .addComponent(K)
                        .addComponent(L)
                        .addComponent(SHIFT)
                        .addComponent(doisPontos)
                        .addComponent(veses)
                        .addComponent(ENTER))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(V)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Z)
                            .addComponent(X)
                            .addComponent(C)
                            .addComponent(B)
                            .addComponent(N)
                            .addComponent(M)
                            .addComponent(CAPS)
                            .addComponent(virgula)
                            .addComponent(ponto)
                            .addComponent(interroga)
                            .addComponent(setaCima)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setaBaixo)
                        .addComponent(setaDireita)
                        .addComponent(setaEsquerda)
                        .addComponent(SPACE))
                    .addGap(23, 23, 23))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents
    
    private void panelPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyPressed
        char tecla = evt.getKeyChar();
        int codigo = evt.getKeyCode();
        switch (codigo){
            case KeyEvent.VK_TAB:
                destacarTeclaDif("TAB");
                break;
            case KeyEvent.VK_ENTER:
                destacarTeclaDif("ENTER");
                break;
            case KeyEvent.VK_BACK_SPACE:
                destacarTeclaDif("BACKSPACE");
                String temp = entradaTexto.getText();
                if(!temp.isEmpty()){
                    temp = temp.substring(0, temp.length() - 1);
                    entradaTexto.setText(temp);
                }
                break;
            case KeyEvent.VK_SPACE:
                destacarTeclaDif("SPACE");
                break;
            case KeyEvent.VK_CAPS_LOCK:
                destacarTeclaDif("CAPS");
                break;
            case KeyEvent.VK_SHIFT:
                destacarTeclaDif("SHIFT");
                break;
            case KeyEvent.VK_DEAD_TILDE:
                destacarTeclaDif("~");
                break;
            case KeyEvent.VK_UP:
                destacarTeclaDif("^");
                break;
            case KeyEvent.VK_DOWN:
                destacarTeclaDif("SETA_BAIXO");
                break;
            case KeyEvent.VK_RIGHT:
                destacarTeclaDif(">");
                break;
            case KeyEvent.VK_LEFT:
                destacarTeclaDif("<");
                break;
            default:
                destacarTecla(tecla);
        }
        
    }//GEN-LAST:event_panelPrincipalKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panelPrincipal.setFocusable(true);
        panelPrincipal.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void panelPrincipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyReleased
        for(Component c : panelPrincipal.getComponents()){
            if(c instanceof JButton){
                JButton botao = (JButton) c;
                String temp = botao.getText();
                if("CAPS".equalsIgnoreCase(temp)){
                    boolean capslock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
                    if(capslock){
                        continue;
                    }
                }
                botao.setBackground(Color.DARK_GRAY);
            }
        }
    }//GEN-LAST:event_panelPrincipalKeyReleased

    private void panelPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelPrincipalFocusLost
        SwingUtilities.invokeLater(()-> panelPrincipal.requestFocusInWindow());
    }//GEN-LAST:event_panelPrincipalFocusLost

    private void panelPrincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyTyped
        char tecla = evt.getKeyChar();
        char temp = Character.toUpperCase(tecla);
        if(teclasPossiveis.indexOf(temp)>=0){
            entradaTexto.append(String.valueOf(tecla));
        }
    }//GEN-LAST:event_panelPrincipalKeyTyped
    
    public void destacarTecla(char tecla){
        tecla = Character.toUpperCase(tecla);
        for(Component c : panelPrincipal.getComponents()){
            if(c instanceof JButton){
                JButton botao = (JButton) c;
                String textoDoBotao = botao.getText();
                if(textoDoBotao.equals(String.valueOf(tecla))){
                    botao.setBackground(Color.blue);
                    break;
                }
            }
        }
    }
    public void destacarTeclaDif(String nomeDoBotao){
        boolean capslock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        for(Component c : panelPrincipal.getComponents()){
            if(c instanceof JButton){
                JButton botao = (JButton) c;
                String comando = botao.getActionCommand();
                if((comando != null && nomeDoBotao.equalsIgnoreCase(comando))||(comando == null && botao.getText().equalsIgnoreCase(nomeDoBotao))){
                    if("CAPS".equalsIgnoreCase(botao.getText())){
                        botao.setBackground(capslock ? Color.blue : Color.DARK_GRAY);
                    }else{
                    botao.setBackground(Color.blue);
                    }
                    break;
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDigitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDigitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDigitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDigitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDigitacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton BACKSPACE;
    private javax.swing.JButton C;
    private javax.swing.JButton CAPS;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton ENTER;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton SHIFT;
    private javax.swing.JButton SPACE;
    private javax.swing.JButton T;
    private javax.swing.JButton TAB;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton abreColchete;
    private javax.swing.JButton barra;
    private javax.swing.JButton doisPontos;
    private javax.swing.JTextArea entradaTexto;
    private javax.swing.JButton fechaColchete;
    private javax.swing.JButton interroga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton ponto;
    private javax.swing.JButton setaBaixo;
    private javax.swing.JButton setaCima;
    private javax.swing.JButton setaDireita;
    private javax.swing.JButton setaEsquerda;
    private javax.swing.JButton tiu;
    private javax.swing.JButton veses;
    private javax.swing.JButton virgula;
    // End of variables declaration//GEN-END:variables
}
