/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.botoes;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class TelaBotoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaBotoes
     */
    public TelaBotoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        onBotao = new javax.swing.JToggleButton();
        aBox = new javax.swing.JCheckBox();
        bBox = new javax.swing.JCheckBox();
        cBox = new javax.swing.JCheckBox();
        botaoCheck = new javax.swing.JButton();
        radioButton = new javax.swing.JPanel();
        cRadio = new javax.swing.JRadioButton();
        bRadio = new javax.swing.JRadioButton();
        aRadio = new javax.swing.JRadioButton();
        dRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        onBotao.setBackground(java.awt.Color.green);
        onBotao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onBotao.setForeground(new java.awt.Color(0, 0, 0));
        onBotao.setText("ON");
        onBotao.setFocusPainted(false);
        onBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBotaoActionPerformed(evt);
            }
        });

        aBox.setText("A");

        bBox.setText("B");

        cBox.setText("C");

        botaoCheck.setText("check");
        botaoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCheckActionPerformed(evt);
            }
        });

        radioButton.setBorder(javax.swing.BorderFactory.createTitledBorder("jRadioButton"));

        grupoRadio.add(cRadio);
        cRadio.setText("C");

        grupoRadio.add(bRadio);
        bRadio.setText("B");
        bRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRadioActionPerformed(evt);
            }
        });

        grupoRadio.add(aRadio);
        aRadio.setText("A");

        grupoRadio.add(dRadio);
        dRadio.setText("D");

        javax.swing.GroupLayout radioButtonLayout = new javax.swing.GroupLayout(radioButton);
        radioButton.setLayout(radioButtonLayout);
        radioButtonLayout.setHorizontalGroup(
            radioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        radioButtonLayout.setVerticalGroup(
            radioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonLayout.createSequentialGroup()
                .addComponent(aRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dRadio)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(onBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCheck)
                    .addComponent(aBox)
                    .addComponent(bBox)
                    .addComponent(cBox))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBox))
                    .addComponent(onBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBotaoActionPerformed
        if (onBotao.isSelected()){
            onBotao.setBackground(Color.red);
            onBotao.setText("OFF");
        }else{
            onBotao.setBackground(Color.green);
            onBotao.setText("ON");
        }
    }//GEN-LAST:event_onBotaoActionPerformed

    private void botaoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCheckActionPerformed
        String texto = "";
        if(aBox.isSelected()){
            texto=texto+"A";
        }
        if(bBox.isSelected()){
            texto=texto+"B";
        }
        if(cBox.isSelected()){
            texto=texto+"C";
        }
        JOptionPane.showMessageDialog(rootPane, texto);
        
    }//GEN-LAST:event_botaoCheckActionPerformed

    private void bRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBotoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aBox;
    private javax.swing.JRadioButton aRadio;
    private javax.swing.JCheckBox bBox;
    private javax.swing.JRadioButton bRadio;
    private javax.swing.JButton botaoCheck;
    private javax.swing.JCheckBox cBox;
    private javax.swing.JRadioButton cRadio;
    private javax.swing.JRadioButton dRadio;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JToggleButton onBotao;
    private javax.swing.JPanel radioButton;
    // End of variables declaration//GEN-END:variables
}
