/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.simuladordecaixa;

import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class TelaNuBanco extends javax.swing.JFrame {
    private float carteira;
    /**
     * Creates new form TelaCaixa
     */
    public TelaNuBanco() {
        carteira=1000;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaMain = new javax.swing.JPanel();
        telaFundo = new javax.swing.JPanel();
        saldo = new javax.swing.JLabel();
        bSacar = new javax.swing.JButton();
        jDepositar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nuBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaMain.setBackground(new java.awt.Color(153, 0, 153));

        telaFundo.setBackground(new java.awt.Color(0, 0, 0));

        saldo.setBackground(new java.awt.Color(204, 204, 204));
        saldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saldo.setForeground(new java.awt.Color(255, 255, 255));
        saldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldo.setText("     SALDO: R$1000.00");

        bSacar.setBackground(new java.awt.Color(153, 0, 153));
        bSacar.setForeground(new java.awt.Color(255, 255, 255));
        bSacar.setText("SACAR");
        bSacar.setBorderPainted(false);
        bSacar.setFocusPainted(false);
        bSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSacarActionPerformed(evt);
            }
        });

        jDepositar.setBackground(new java.awt.Color(153, 0, 153));
        jDepositar.setForeground(new java.awt.Color(255, 255, 255));
        jDepositar.setText("DEPOSITAR");
        jDepositar.setBorderPainted(false);
        jDepositar.setFocusPainted(false);
        jDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("     Digite um valor para deposito/saque");

        entrada.setBackground(new java.awt.Color(40,40,40));
        entrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entrada.setForeground(new java.awt.Color(255, 255, 255));
        entrada.setBorder(null);
        entrada.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(40, 40, 40));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R$");

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaFundoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(telaFundoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(telaFundoLayout.createSequentialGroup()
                                .addComponent(bSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        nuBanco.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nuBanco.setForeground(new java.awt.Color(255, 255, 255));
        nuBanco.setText("NuBanco");

        javax.swing.GroupLayout TelaMainLayout = new javax.swing.GroupLayout(TelaMain);
        TelaMain.setLayout(TelaMainLayout);
        TelaMainLayout.setHorizontalGroup(
            TelaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nuBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(telaFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        TelaMainLayout.setVerticalGroup(
            TelaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuBanco)
                .addGap(18, 18, 18)
                .addComponent(telaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void bSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSacarActionPerformed
        try{
            float temp = Float.parseFloat(entrada.getText());
            if(temp>carteira){
                JOptionPane.showMessageDialog(TelaMain, "Saldo Insuficiente!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }else if(temp<=0){
                JOptionPane.showMessageDialog(TelaMain, "Valor Inválido para Saque!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }else{
                carteira=(carteira-temp);
                saldo.setText("     SALDO: R$"+String.format("%.2f", carteira));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(TelaMain, "Valor Inválido para transação!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        entrada.setText(" ");
    }//GEN-LAST:event_bSacarActionPerformed

    private void jDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositarActionPerformed
        try{
            float temp = Float.parseFloat(entrada.getText());
            if (temp<=0) {
                JOptionPane.showMessageDialog(TelaMain, "Valor Inválido para Depósito!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }else{
                carteira=(carteira+temp);
                saldo.setText("     SALDO: R$"+String.format("%.2f", carteira));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(TelaMain, "Valor Inválido para transação!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        entrada.setText(" ");
    }//GEN-LAST:event_jDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNuBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNuBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNuBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNuBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNuBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaMain;
    private javax.swing.JButton bSacar;
    private javax.swing.JTextField entrada;
    private javax.swing.JButton jDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nuBanco;
    private javax.swing.JLabel saldo;
    private javax.swing.JPanel telaFundo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
